### ISSUE TITLE
EfficientDetLite0

### ISSUE THREAD

**Issue by soyebn** [rwightman/efficientdet-pytorch#31] opened 2020-06-06 15:42 UTC
I am curious to know your view on efficientnetLiteB0 as a backbone. Google has officially not released but do you think switching backbone from efficientnetB0 to efficientnetLiteB0 will make coco AP degrade less than 5% of original or it will degrade more? 

In the current code base, if I call efficientnetLiteB0 from your timm model collection, will it work?

**Comment by rwightman** [comment] 2020-06-06 16:16
You also need to add the efficientdet config, I actually have efficientdet_lite0 one on the `model_configs` branch along with some other experimental configs, I haven't tested them, and haven't trained any, but they should work and train using the timm checkpoints as the starting point.

https://github.com/rwightman/efficientdet-pytorch/tree/model_configs

**Comment by rwightman** [comment] 2020-06-06 16:17
it's `tf_efficientdet_lite0` because I never trained a non tf ported version of the lite models in timm ... the mobilenetv2, v3, and mixnet variants have non tf_ versions...

**Comment by rwightman** [comment] 2020-06-06 16:19
oh, and one more catch, it requires this branch of `timm` right now https://github.com/rwightman/pytorch-image-models/tree/densenet_update_and_more

hoping to get both merged in a few days with a new timm release

**Comment by soyebn** [comment] 2020-06-06 17:36
Thanks a lot again. I will give it a try and let you know.

**Comment by rwightman** [comment] 2020-06-07 02:15
@soyebn thanks for the update, curious to see how it works out... did you use the training hparams (command line) in my last update? if it ends up with half-decent results I'll add them to the pretrained weights here with a mention if you're open to sharing.

**Comment by soyebn** [comment] 2020-06-07 06:44
I have used the training command mentioned in the usage section,
**./distributed_train.sh 2 /mscoco --model tf_efficientdet_d0 -b 16 --amp --lr .04 --warmup-epochs 5 --sync-bn --opt fusedmomentum --fill-color mean --model-ema**
So here is the difference wrt your last command,
LR is fine as Usage command has done right scaling, However other three parameters are different.
|Option|Usage cmd| Last Update cmd|
|----------|:-------------:|------:|
-fill-color| mean |0
--lr-noise  |None |0.4 0.9
--model-ema-decay| 0.9998 | 0.9999

I am tempted to continue with the training as I have already got 25.1 AP in just 22 epochs. What do you suggest? 
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.251

Btw, I will be glad to share back trained weights and results. Thanks a lot.

**Comment by rwightman** [comment] 2020-06-08 05:47
@soyebn the LR is good there so should be an okay result. It starts off pretty good in the first 50-80 epochs then slows down..  the increments are very small after 100 or so epochs and sometimes there are long periods of down trend before it goes back up, requires patience and not very exciting :)

**Comment by soyebn** [comment] 2020-06-09 14:29
It is going exactly as you pointed out. It has reached 29.91% at 128 Epochs.

**Comment by soyebn** [comment] 2020-06-13 15:48
@rwightman. Training got completed today. I got 31.81% mAP (iou 0.5:0.95.) this is just 1.81 lower than efficientdet_d0. Definitely better than I anticipated. :-)
One question on validation. When I tried to run validation on the best model, I got 30.91% vs expected 31.81% reported during training. I am using the following command for validation,

**python validate.py ./data/mscoco/ --model tf_efficientdet_lite0 --checkpoint ./output/train/20200607-000700-tf_efficientdet_lite0/model_best.pth.tar --no-redundant-bias**

Am I doing anything wrong?
Regarding sharing back trained model, How do I share it with you?

**Comment by rwightman** [comment] 2020-06-13 16:52
@soyebn try using the --use-ema arg for validate command, the train checkpoints contain both a normal and ema version of the weights, the checkpoint loader defaults to the normal unless that flag is enabled.

also, give checkpoint averaging a try, hopefully you kept your train folder... 

run `python avg_checkpoints.py --input path/to/output/train/dated_folder --output my_averaged_mode.pth -n 8. ... try n of 5, 8, 10 ... (the avg script defaults to ema and outputs a checkpoint with just the final state dict) .... you may end up with a small bump

**Comment by soyebn** [comment] 2020-06-13 18:31
@rwightman,  
You are right. After I added support for arg --use-ema in validate in model_config branch, it gave me exactly same acc as that was shown during training. 
Also with avg_checkpoint(n=8) it increased to 32.0 (iou=0.5:0.95) and 50.0 (iou=0.5).

--------------------------------------------------------------------------------------------------------
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.320
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.500
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.336
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.111
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.378
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.502
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.278
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.430
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.455
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.180
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.539
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.680

**Comment by rwightman** [comment] 2020-06-13 18:54
@soyebn great, is the resulting checkpoing under 25MB? you might be able to zip it and attach it to a comment here... otherwise any public url via google docs, dropbox, custom web server, etc would work, I'll download and comment when done so you can take it down

**Comment by soyebn** [comment] 2020-06-13 19:15
It was around 40 MB so sharing in google drive. Pls let me know when you have downloaded.
https://drive.google.com/file/d/1XLBAf6hpcnqfyKz7MTqHefc0m78_BVQi/view?usp=sharing.

I had another question. When I exported tf_efficientdet_lite0 model it created complicated ONNX graph whereas when I exported efficientdet_lite0 it was much cleaner ( i added relevant config for this). So I wanted to repeat whole training exercise with efficientdet_lite0. I guess first I need to do imagenet training to get efficientnet-lite0. Are configs properly defined for efficientnet_lite0 and can I do training in similar manner?

**Comment by rwightman** [comment] 2020-06-13 20:00
@soyebn k, I've downloaded it

a few options, the one you mention is to

1. train the efficientnet_lite0 yourself, the example command I have on pytorch-image-modles for training the effiicientnet_b0 to 77.7 should work well for lite0 ... it's a 2 GPU distributed training command line.. if you're using 1 GPU you could just eliminate the distributed, possibly leave the batch size as is and halve the learning rate ... there are no non tf_ configs in here yet but that's a simple cut and paste and removing the tf_ set padding='' (instead of 'same') and redundant_bias=False in the config

2. I have a series of pretrained mobilenetv2 models which are actually VERY close to the lite versions of EfficientNet. The '110d' model I made is a bit deeper than the normal mobilenet and hit 75.02, They should have the same type of graph as EfficientNet-Lite as there are no swish activations 

3. Use the pretrained tf_ weights from `timm` as the starting point for a non tf_ efficientdet-lite model here. You will need to download the checkpoint manually and probably add a hack to load that into the backbone instead of pretrained, the weights are actually cross compatible, but without the same padding there is a loss in performance, it might not be a big factor since it's just the starting point

4. try optimizing your onnx model, it may prune out some of the extra cruft. https://github.com/rwightman/gen-efficientnet-pytorch/blob/master/onnx_optimize.py

**Comment by soyebn** [comment] 2020-06-14 09:09
@rwightman , regarding your suggestion #4, when I tried to run onnx_optimize on  tf_efficientdet_lite0 I get the following error. I had to use opset=11 for onnx export to succeed in the first place. My onnx version is 1.7.0 (pypi).
**field = STORAGE_TENSOR_TYPE_TO_FIELD[attr.t.data_type]
KeyError: 10**
Whereas just for sanity test when I ran on efficientdet_lite0, onnx_optimize works.

For #3 is it possible to load weigths from tf_effcientdet_lite0 what I trained just now. That will save me 1 week or so. If not then I am inclined to try your suggestion #1 as it is more easily reproducible.

**Comment by rwightman** [comment] 2020-06-20 23:24
@soyebn I missed the question there last week... loading the weights directly into the non tf detection model is possible but you'd see a fairly significant drop (if you hadn't tried already)... when that's done for the pretrained classifier backbone, the impact on the end detection model should be insignificant

**Closed by rwightman** 2020-06-20 23:24 UTC

**Comment by ryusaeba** [comment] 2020-10-22 05:36
@rwightman @soyebn  thank you for both great work.  It's glad to find someone who is able to train efficientdet-lite0 from scratch based on imagenet pretrained weight. I am also interested about this, so there has few more question to you. 
Q1: Have you tried to train other version such as lite1/2? 
Q2: If I would like to reproduce your experiments, all what I needed is to follow this discussion thread?

Many Thanks for both :)

**Comment by soyebn** [comment] 2020-10-22 17:44
I have not tried lite1/2 yet. I am curious to see what accuracy you get with those?
Yes. Just follow the steps mentioned in the thread. You just need some patience. :-)

**Comment by ryusaeba** [comment] 2020-10-23 00:58
Thanks for the quick response. I will follow the steps to reproduce the lite0 first. Once the lite0 is done, will continue to try lite1/2. Will update you once I get the accuracy :)

**Comment by isaacrob** [comment] 2021-03-16 21:59
Hello! @ryusaeba @rwightman @soyebn this is very exciting :) have any of you finished training lite1/2/3/4 variants, and if so, would you be willing to share the weights as @soyebn did for lite0?

**Comment by ryusaeba** [comment] 2021-11-12 07:47
Sorry, I still not try yet.

**Comment by soumendukrg** [comment] 2021-11-15 18:46
The google [automl repository](https://github.com/google/automl/tree/master/efficientdet) have checkpoints for 6 efficientdet_lite models. Can we directly use these weights with the tf versions of the lite models? I do see that you already have the model configurations in your config file.

**Comment by rwightman** [comment] 2021-11-16 04:34
@soumendukrg I have a WIP update with support for official lite models, but it required supporting feat sizes that aren't divisible by 128 so ended up being significant and need to test quite a few things before I can proceed

**Comment by soumendukrg** [comment] 2021-11-16 04:39
Thanks for the response. I will wait for the update.
________________________________
