### ISSUE TITLE
Comparison with YoloV5

### ISSUE THREAD

**Issue by jinfagang** [rwightman/efficientdet-pytorch#81] opened 2020-09-21 08:11 UTC
Hi, I am wondering, if anyone could do a experiement on compare with YoloV5 s/l/x under same resolution input? To figure out which one is the best for now, also include the latency it needed?

**Comment by rwightman** [comment] 2020-09-23 01:10
@jinfagang I'm closing this as it's not a bug or feature request, feel free to open as a discussion when I get discussions support enabled.

**Closed by rwightman** 2020-09-23 01:10 UTC
